# Generated by Django 5.1.1 on 2024-09-17 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reviewitem_delete_moodentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
