# Generated by Django 5.1.1 on 2024-09-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reviewitem_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
