# Generated by Django 5.1.1 on 2024-09-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reviewitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewitem',
            name='username',
        ),
    ]
