# Generated by Django 5.1.1 on 2024-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_additem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='photo',
        ),
        migrations.AddField(
            model_name='additem',
            name='photo_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
