# Generated by Django 5.1.1 on 2024-09-30 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_additem_photo_additem_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.additem'),
            preserve_default=False,
        ),
    ]
