# Generated by Django 5.1.1 on 2024-10-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reviewitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewItem',
        ),
    ]
